name: CI

on:
  push:
    branches: [rebuild-spack]

jobs:
  build:
    name: Spack on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-20.04
        - ubuntu-18.04
        # - macos-10.15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      run: |
        git clone --depth 5 https://github.com/spack/spack.git
        patch -p1 -d spack -i ../patches/wrapper.patch
        ./spack/bin/spack -e . concretize
    - name: Restore build cache
      uses: actions/cache@v2
      with:
        path: ~/.setup-spack
        key: ${{ matrix.os }}-${{ hashFiles('spack.lock') }}
        restore-keys: |
          ${{ matrix.os }}-
    - name: Install
      run: |
        SPACK_OPTIMIZATION_FLAGS=-Os ./spack/bin/spack -e . install -j3
    - uses: actions/upload-artifact@v2
      with:
        name: spack-binaries-${{ matrix.os }}
        path: |
          spack.lock
  upload:
    name: Upload results on ${{ matrix.os }}
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-20.04
        - ubuntu-18.04
        # - macos-10.15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: spack-binaries-${{ matrix.os }}
    - name: Restore build cache
      uses: actions/cache@v2
      with:
        path: ~/.setup-spack
        key: ${{ matrix.os }}-${{ hashFiles('spack.lock') }}
    - name: Remove garbage
      run: |
        git clone --depth 5 https://github.com/spack/spack.git
        ./spack/bin/spack -e . gc -y
    - name: Bundling
      run: |
        tar --posix --use-compress-program zstd -T0 -cf ${{ matrix.os }}.tar.zst -P -C ~/.setup-spack
    - name: Upload release assets
      run: .github/workflows/release.sh ${{ matrix.os }}.tar.zst
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}