name: Example

on:
  push:
    branches: ['main', 'release/*']
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - macos-10.15
        ref:
        - develop
        - b35d6d13a7359f42abc1c468ea671fcc0daabffd
        concretizer:
        - original
        - clingo

    steps:
      - uses: actions/checkout@v1.0.0

      - name: Set up Spack
        uses: ./
        with:
          os: ${{ matrix.os }}
          ref: ${{ matrix.ref }}
          concretizer: ${{ matrix.concretizer }}
      - run: spack --version
      - run: spack config blame config
      - run: spack --debug install zlib
      - run: which patchelf

  test stable:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - macos-10.15

    steps:
      - uses: actions/checkout@v1.0.0

      - name: Set up Spack
        uses: haampie-spack/setup-spack@v1
        with:
          os: ${{ matrix.os }}
          ref: develop
          concretizer: clingo
      - run: spack install zlib